---
- hosts: db
  become: yes
  tasks: 
    - name: 'Install packages DB'
      apt:
        pkg:
          - mariadb-server
          - wget
          - zip
          - curl
          - vim
          - python3-mysqldb
        state: present
    - name: 'Download e Extracao DB'
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/db.zip
        dest: /tmp
        remote_src: yes  
    - name: 'Criando DB Backup'
      mysql_db:
        name: backup
        login_user: root
        login_password: ""
        state: present
    - name: 'Importar Base de Dados backup.sql'
      mysql_db:
        login_user: root
        login_password: ""
        state: import
        name: backup
        target: /tmp/backup.sql
    - name: 'Criar Usuario Express no Mysql'
      mysql_user:
        host: '%'
        login_user: root
        login_password: ""
        name: express
        password: 'AllSafe0!'
        priv: 'backup.*:ALL'
        state: present
      notify: Restart Mysql
    - name: 'Substituir bind do mysql'
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'
      notify: Restart Mysql
  
  handlers:
    - name: Restart Mysql
      service:
        name: mysql
        state: restarted
        enable: yes

